// Code generated by protoc-gen-go.
// source: pb3.proto
// DO NOT EDIT!

/*
Package pb3 is a generated protocol buffer package.

It is generated from these files:
	pb3.proto

It has these top-level messages:
	Any
	Element
*/
package pb3

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Any struct {
	TypeUrl string `protobuf:"bytes,1,opt,name=type_url" json:"type_url,omitempty"`
	Value   []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Any) Reset()         { *m = Any{} }
func (m *Any) String() string { return proto.CompactTextString(m) }
func (*Any) ProtoMessage()    {}

type Element struct {
	Wtf bool   `protobuf:"varint,1,opt,name=wtf" json:"wtf,omitempty"`
	Sid string `protobuf:"bytes,2,opt,name=sid" json:"sid,omitempty"`
	Nid int64  `protobuf:"varint,3,opt,name=nid" json:"nid,omitempty"`
	Pos int64  `protobuf:"varint,4,opt,name=pos" json:"pos,omitempty"`
}

func (m *Element) Reset()         { *m = Element{} }
func (m *Element) String() string { return proto.CompactTextString(m) }
func (*Element) ProtoMessage()    {}

func init() {
}
